### PR TITLE
Rewrite Poseidon hash implementation (WIP)

### PR DESCRIPTION
**Pull request by poma**
Rewrite Poseidon hash implementation to be compatible with reference implementation	at https://extgit.iaik.tugraz.at/krypto/hadeshash

Changes:
- Uses secure pregenerated constants from https://extgit.iaik.tugraz.at/krypto/hadeshash/-/blob/master/code/generate_parameters_grain.sage
- Doesn't reuse constants between hashes with different `t`
- Doesn't reuse constants between rounds
- Automatically picks `t`, `Rf`, `Rp` based on tables in the whitepaper https://eprint.iacr.org/2019/458.pdf
- Doesn't apply matrix multiplication in the last round

To Do

- [x] Circom implementation
- [x] JavaScript implementaion
- [ ] Solidity implementation

### CODE REVIEW

**Comment by HarryR** [comment]
I'd be interested to see the Solidity implementation, because certain liberties have been taken to keep it cheap on EVM.

See: https://github.com/Loopring/protocols/blob/master/packages/loopring_v3.js/src/poseidon.js for reference code.

**Comment by poma** [comment]
I don't know evm asm well enough to write an optimal implementation so I think someone else needs to update the current one to be compatible

**Comment by jbaylina** [comment]
I merged it by hand . So I close this PR.

Thank you very much for the contribution.!

**Comment by weijiekoh** [comment]
@poma Thank you for this! What was the value of the `field_size` you chose to input in `generate_parameters_grain.sage`?

**Comment by poma** [comment]
`sage generate_parameters_grain.sage 1 0 254 2 8 56 0x30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f0000001`, see https://github.com/iden3/circomlib/blob/master/src/poseidon.js#L10

**Pull request closed without merging**
